### ISSUE TITLE
Training a 25x1 zero AI using SAI

### ISSUE THREAD

**Issue by wonderingabout** [CuriosAI/sai#10]
hi everyone ! :+1: 

25x1 is an unknown yet very fun board size !

many players, especially dan players, enjoyed playing it as they were introduced to it, then they wanted to know more about it

A friend of mine also had a plan to start to train a bot for 25x1, several months ago

You can find an example of how 25x1 is played in these 2 game samples

- 1 : https://online-go.com/game/10672030
- 2 : https://online-go.com/game/14322214

it's a game heavily revolving arround ko reading, but also using concepts of influence, territory, sente, etc...
so i want to run it on OGS (i'm already running phoenixgo on ogs)

zero bot (no previous knowledge), chinese rules, 1.5 komi, all rules same as 19x19

as for me i have no past knowledge on training an AI but i'm very motivated to do it, so i would appreciate any guidance even if the slightest, step by step let's make it !

i have a general idea of how AI are trained (selfplay until enough game data is produced, then train a new network on this data, if it is stronger than previous best promote it and make it strong

some quick things i thought about (will be updated with time) : 

- 25x1 is not a square board size, but gtp2ogs is compatible with any custom board size now
- 25x1 is not a square board size, so code may need to be modified to support custom width and height (who said go cant be played on non square board sizes)
- if 1.5 komi is too good for black, i think the sai approach allows me to change komi, does it make the training slower or weaker as compared to one komi approach ?
- symetries are uneeded considering how small the board is
- i have some feel like let's start with a 10b size then maybe increase to 15-20b size
- i want to start training it alone, then depending on how successfuly i am, i may open source it and make it in autogtp mode (not urgent)

@Vandertic @Francesco Morandin @parton69 @amato-gianluca @nazgand @bood

**Comment by wonderingabout** [comment]
update : 

as i was advised, i'll start first to train a supervised network for 19x19, and when i get experience on this then i'll come back to ask for help and advice on the code for 25x1

by that time, i'm open to any suggestion :+1:

**Comment by alreadydone** [comment]
References:
https://senseis.xmp.net/?LinearBoards
https://pdfs.semanticscholar.org/036a/013a005c14c9a625984b3522969ef5c9e0cb.pdf (fairly recently paper, but didn't train a NN for move ordering)
http://webdocs.cs.ualberta.ca/~hayward/396/ssgo.pdf

+ Current code indeed only includes one board size instead of two sizes (height and width), and may or may not have problem with even board sizes.
+ You probably want 1x? convolution kernels to save more than 1x computation over current 3x3 (or maybe make all layers fully-connected if kos are abundant); that would require going into the NN code (convolve3.opencl, etc.) as you are changing the architecture of NN.

**Comment by wonderingabout** [comment]
i'm taking note of all this @alreadydone , big thanks :+1: 

yes 25x1 revolves heavily arround ko, so if its possible to sharpen its reading on ko it would be great

and yes as you said width x height is one of the first issues to fix on the code

**Comment by Vandertic** [comment]
Hi @wonderingabout that is one cool project!

Now some comments:

Changing the 3x3 convolution code would be hard indeed, in particular if you want OpenCL acceleration (i.e.: use GPU). I would suggest to leave the net structure as it is, initially. 3x3 convolutions are probably a bit overkill for 25x1, but since the board is virtually 27x3, with "virtual" intersections all around real ones, that should work eventually.

The code both of LZ and SAI relies everywhere on the board be square and with odd size. You must be very careful.

The training data in particular code every board-sized bit plane with a string of hex digits, 4 bit each. For example 19x19=361=1+4*90, so for 19x19 the training data codes the bit planes with 91 digits long strings.

As for the komi, truly SAI would allow not only to change komi, but also to determine the fair komi with high precision. For example SAI concluded that with area scoring the fair komi is 9 on 7x7 and 7 on 9x9.

To train SAI you just need to be able to train LZ and then change the normal pipeline by generating branches of games starting at any positions and changing komi in a suitable way. I can be more specific when you will be ready.

Just to simplify things, after some practice with supervised training, I would suggest to install a small server of yourself, just for personal use, and start using autogtp. It is much easier to automate things...

**Comment by wonderingabout** [comment]
@Vandertic 

big thanks for the step by step explanation

a few things since last time : 
- i was contacted by my friend for 25x1 : he told me has an already working 25x1 code and has trained his 25x1 bot with quite good results already, but the code is written in C and is ugly according to him. I asked if he wants to share it, but he told me he's busy and he would have to look at which parts to clean, etc, so i'll update you and everyone here on this (we may take whatever is usable on his code maybe, or simply just use SAI as you explained, if he is willing to share it)
- another friend of mine gave me a link to 40k human sgf so i also have the option to train on these (or LZ/elf training data), the result 19x19 AI doesnt matter much to me as its a way to gain experience for me, but if it turns out to be interesting why not use it, later

general notes : 
- for fair komi, this is interesting indeed, even if a different value is chosen, the bot's opinion will be taken into account
- then it's as you say, i need first to practice enough with supervised training, and seeing how LZ is popular and documented, i think it's wise to go with LZ
- your general explanation helps me picture the general idea of it, i'm sure it will be helpful to help me grasp the general concepts and look into directions to dig into
- as for hardware acceleration, we all have GPUs here so it would be a shame not to use the much more powerful hardware, so i think it's worth making some extra efforts to make it compatible

thanks again, i'll update this topic from time to time to feedback and/or ask for help :+1:

**Comment by wonderingabout** [comment]
update : 

i just want to mention i didnt forget about this :+1: 

doing other code related things to it, but this is a long-term project i definitely want to do :100:

**Comment by wonderingabout** [comment]
update 2 : 

as i'm focused on other things, it may take longer than expected to start this, so closing this issue for now to avoid burdening this issues place :+1: 

i'll update this and maybe reopen if i have news :100:
