### ISSUE TITLE
What should I read to implement this for Blooms?

### ISSUE THREAD

**Issue by Nazgand** [CuriosAI/sai#11]
I am wondering if some documentation or a manual exists. Suggestions and help would be appreciated.

Go with 2 colors per player on a hexagonal board.
https://boardspace.net/blooms/english/rules.html

---------------------------
Separate a move into 2 moves.

Neural Network Inputs:
Hexagon tiled board (has 12 symmetries) of the last 4 board states
    • an input set of the current player’s blooms
    • an input set of the ally’s blooms
    • 2 input sets of the opponent’s 2 bloom colors
1 bit for ally moving next or opponent moving next

Expressing hexagons as sums of multiples of (-1)^(2/3) and multiples of 1 allows easy symmetry computation by taking the complex conjugate or multiplying by (-1)^(1/3).

The network has the symmetry of swapping the opponent’s colors.
The if an ally color moves next, then the network has a symmetry of swapping the current color with the allied color because capturing only happens when the color switches teams.

The length n edged board has [1-3*n+3*n^2] territories.

Use a Tromp-Taylor analog for scoring.
---------------------------

This seems strange to me (why +2?) in FastBoard.h:
static constexpr int MAXSQ = ((BOARD_SIZE + 2) * (BOARD_SIZE + 2));

Do I need to have an extra layer of territories around the board?

**Comment by Vandertic** [comment]
In FastBoard class the goban is virtually enlarged by 2 intersections on both directions, so 9x9 is actually 11x11 for example. The border of virtual intersections is useful to compute liberties and captures, because they are set to be both white and black at the same time (or so it seems).
So there are basically two different ways if indexing the intersections of the board, one with the real BSxBS board, and one with the virtual (BS+2)x(BS+2).
I don't understand everything in that part of the code either, but it seems correct and well written to me.
