### ISSUE TITLE
What do the numbers mean in comments?

### ISSUE THREAD

**Issue by kennyfs** [CuriosAI/sai#13]
`-1.24, -9.17, 0.0556, 0.375, 0.491, 0, 1`
`1.07, 2.61, 0.0583, 0.538, 0.497, 0, 0`
I found some numbers in the comments. 
Can anyone tell me what they mean?

**Comment by Vandertic** [comment]
I need to find more time to write proper documentation. Anyway... SAI nets give the policy like LZ, and instead of value (aka win-rate) they give two parameters alpkt and beta.

- **alpkt** is more or less the points in favor of black, including komi
- **beta** is a measure of certainty of the score

The numbers in the comments are, as described in the comment of the first move...

- **alpkt_online_median**, approximate median of alpkt over the move explored subtree,
- **alpkt**, raw network estimate of alpkt (more noisy), 
- **beta**, raw network estimate of beta, if above 1 the score is almost decided,
- **pi**, raw network win-rate estimate at current komi, for black, 
- **agent_eval_avg**, average of agent win-rate over the move explored subtree (if lambda=0 as is for the games on the server, agent is the same as LZ, see the paper),
- **agent_x_lambda**, size of the integration interval (useful only if lambda>0),
- **is_bluder**, flag, useful only for self-plays, a random move may be a blunder (if if loses at least 5% win-rate probability) in that case training info is saved only after last blunder

In matches the comments are those of the black network, and **is_blunder** flag has no use (and alternates between 0 and 1, at the moment)

**Comment by kennyfs** [comment]
Great answer.
Now I have another question that why the numbers are 
`0,0,1,0.5,0.5,0,(1or0)`
in the beginning moves?
I often find my computer say it's loading a sgf with xxx moves, where do they come from? 
I think they are linked.

**Comment by amato-gianluca** [comment]
I leave to Francesco the answer to your question about the numbers at the beginning of the match. Regarding the SGF's which are downloaded by SAI, they come from previous selfplays which are saved in our server sai.unich.it.

When a selfplay terminates, we upload to the server both the result of the game (like Leela does) and the corresponding SGF. Later on, the SAI server may ask a client to start from a specific point of a previous selfplay, but using a different komi. We use this approach to help the network learn the  advantage of black over white (the alpkt value) in different positions.

**Comment by Vandertic** [comment]
Yes. Those are the _branches_ games that are really useful to train SAI value head.
When a self-play game is a branch of a previous game, the old moves from the previous game sgf have no comment data, and hence you find those numbers instead.

**Comment by kennyfs** [comment]
Then, how about the numbers in match games?
I discover the two close moves have the same number, why?

**Comment by Vandertic** [comment]
Because autogtp takes the sgf from a single player, during matches. (Always Black.)

In the way it is working now we lose the comments of White player. This is a pity and something that would be wonderful to improve upon. Alas, it is not very urgent.

**Comment by kennyfs** [comment]
I agree with you.
After all, match games aren't for training.

Vandertic <notifications@github.com> 於 2019年10月26日 週六 16:35 寫道：

**Comment by kennyfs** [comment]
The number from search in alpkt value is behind the raw one, but the pi is the opposite.  Could you edit it in the next version so that it'll be read more easily?

**Comment by Vandertic** [comment]
You are right. I will.

**Comment by kennychenfs** [comment]
I see the is_bluder is 3 in some games.  What does it mean?  I guess it is a big mistake, but how big it is?

**Comment by Vandertic** [comment]
Actually, in the end we didn't correct this thing. The reason is that it is quite sensible to have the three net estimate (alpkt, beta and pi) held together.
Also, notice that the agent_eval_avg is the average of win-rates as given by the lambda-mu agent, while pi is the raw net win-rate without considering the agent.

So the order is: alpkt_median, alpkt, beta and pi, agent_eval_avg, agent_bonus, bitfiled.
