### ISSUE TITLE
why let net 36 run test match with so many nets whose hash begining e and f

### ISSUE THREAD

**Issue by l1t1** [CuriosAI/sai#27]
is this a bug?

**Comment by kennyfs** [comment]
if gen is a multiple of 4, panel matches are added between the 16 networks
in the panel
<https://github.com/sai-dev/sai/wiki/Panel-of-reference-networks> and
chosen_net, again to get an even more precise evaluation of chosen_net Elo.
These matches can be identified because they are 30 games long;
in wiki/process
I don't know why most nets have a beginning of e or f.

l1t1 <notifications@github.com> 於 2019年10月30日 週三 03:31 寫道：

**Comment by l1t1** [comment]
thanks

**Comment by l1t1** [comment]
all hash begin of e or f again

![2019-10-31_101933](https://user-images.githubusercontent.com/23301704/67913446-11ab9800-fbc8-11e9-9830-c7e33cbd0504.png)
![2019-10-31_101857](https://user-images.githubusercontent.com/23301704/67913448-11ab9800-fbc8-11e9-835c-a7915fbb98dd.png)

**Comment by Vandertic** [comment]
This happens every 4 networks. Those are the matches with the "panel" of 16 nets

**Comment by l1t1** [comment]
i see the step from  kennychenfs' reply, but i wonder why all 16 panel nets are begin of e or f.

**Comment by Vandertic** [comment]
The panel should be made of nets with all levels of strength. An easy way to approximate this property is to choose the last nets in hash alphabetical order

**Comment by Vandertic** [comment]
I have written some [documentation](https://github.com/sai-dev/sai/wiki/Panel-of-reference-networks).
