### ISSUE TITLE
what is the portion of different komi games in matches

### ISSUE THREAD

**Issue by l1t1** [CuriosAI/sai#31]
and how to ensure the promoted net with biggest winrate in komi 7.5

**Comment by Vandertic** [comment]
All matches SAI-net vs SAI-net are currently at komi 7.
The matches of SAI-net vs LZ-net are at komi 7.5, since LZ plays with thah fixed value.

The promoted net is the one with the higher score against the previous one, in the block of ten "50-games matches" that usually starts towards the end of each generation self-plays.

**Comment by l1t1** [comment]
so the promote matches are all kimo 7?

**Comment by Vandertic** [comment]
Yes
