### ISSUE TITLE
sai 90  with 400 vists failed on ladder

### ISSUE THREAD

**Issue by l1t1** [CuriosAI/sai#51]
validation -g 2 -k sai90_lz251 -n cc3.gz -o "-g -v 400 -r 5 -w" -n networks/b346eff6bd20d5e9e2229549916c323a9f3b42e60ecd0a4e16903f4a6967a069.gz -o "-g -v 1 -r 5 -w" -- sai -- sai
[white_50fde4ca8b294304ac563fc46ae25c9f.sgf.txt](https://github.com/sai-dev/sai/files/3849891/white_50fde4ca8b294304ac563fc46ae25c9f.sgf.txt)
sai 87 also has the shortcoming
[black_2fa493bcab724b2b9cbc92f5785529d2.sgf.txt](https://github.com/sai-dev/sai/files/3849900/black_2fa493bcab724b2b9cbc92f5785529d2.sgf.txt)

**Comment by Vandertic** [comment]
I'd like to remark that SAI has not particular advantage over LZ in reading ladders. It just has some liberty planes that may help ladder exploration.

Anyway I have some simple ideas to improve SAI at ladders. So as soon as there is some time and SAI is strong enough, I will be glad to be shown some ladder-critical fuseki, so that we can test and fine-tune these ideas.

**Comment by jfbaraton** [comment]
Hi, if you are still interested in a ladder fuseki:
http://files.gokgs.com/games/2021/11/25/tku-minisai.sgf
https://ai-sensei.com/game/5e5wITsYOoXfQQBkkZ5LATh5RJA2/Nd4PMhXKHXyH4RfrOPBw

"minisai" is sai (best 12b) with 8 p0 on raspberry pi4
