### ISSUE TITLE
gtp options

### ISSUE THREAD

**Issue by kennyfs** [CuriosAI/sai#84]
I see "--recordvisits" in selfplay games, but I don't get anything in my test.  Can you explain how it works?
btw, I'm also curious in other options.

**Comment by Vandertic** [comment]
There is a short description if you run `sai --help` and much more if you can find the relevant commit.
Anyway `--recordvisits` has only effects in self-plays as it changes the way policy target is written inside training chunks. It basically suppresses the normalization to 1, hence writing the integer number of visits instead of the floating point scaled value. This is both more precise (no approximations), more informative (you can recover and check the number of visits) and more concise (of 362 moves many have 0 to 9 visits and hence a single text character can hold the information.
